### ISSUE TITLE
@ parsing issue

### ISSUE THREAD

**Issue by vuvova** [NyanNyanovich/nyan#3]
https://t.me/nyannews/8265
> Как передает телеграм-канал «Ху Херсон» со ссылкой
> ... — [Медуза — LIVE](https://t.me/meduzalive/67955)

but if one follows the link to see the meduzalive message, it was
> Как передает телеграм-канал «Ху@вый Херсон» со ссылкой

**Comment by NyanNyanovich** [comment]
Thank you, I fixed it, closing the issue.
