### ISSUE TITLE
when possible, prefer a neutral source for a quote?

### ISSUE THREAD

**Issue by vuvova** [NyanNyanovich/nyan#4]
example: https://t.me/nyannews/8328

red version: https://t.me/uranews/65570
blue version: https://t.me/radiosvoboda/27194
neutral version: https://t.me/rbc_news/57069

**Comment by NyanNyanovich** [comment]
It should be the case already: https://github.com/NyanNyanovich/nyan/blob/main/nyan/title.py#L36
The problem with the given example is that all neutral versions appeared _after_ the post in Nyan.
