### ISSUE TITLE
Сделал форк 

### ISSUE THREAD

**Issue by mindfulme** [NyanNyanovich/nyan#6]
Добавил фильтр новостей и каналов, новости выходят намного чаще (раз так в 100 чаще). Поменял логику того как выходят посты, теперь существенно больше контента (фото, видео) и меньше скучного текста. Получился такой себе новостной тикток. 

Выложу свой форк на гитхаб после мелких доработок

Бамп https://t.me/upnewsua/14457

**Comment by NyanNyanovich** [comment]
Круто! Сделал список внешних каналов в Readme.
