### ISSUE TITLE
[Suggestion] Generate a summary of all News throughout some time interval.

### ISSUE THREAD

**Issue by SolAstri** [NyanNyanovich/nyan#8]
I'm not really sure if that's the correct place to send an issue to, considering the feature lies a bit outside of the nyan's domain (and requires using LLM, probably), but it'd be perfect to have it.

Perhaps, we need some kind of ranking (in terms of importance and societal resonance, that is) to select the final collection? Or just a general summarization, idk, that's still something to think about.

**Comment by Nyan404** [comment]
Agree. It would be nice to receive a selection in one post in the format:
"The most popular of the day"

**Comment by NyanNyanovich** [comment]
Done, see [summary.py](https://github.com/NyanNyanovich/nyan/blob/master/nyan/summary.py)
I use GPT-4, GPT-3.5 should also work to some extent.
Importance ranking is performed by the GPT itself based on views, source count, and its own understanding.
The price is around 1$ per day. Note that I also have a test channel, and it is an overall cost.
I'm 99% sure that there are no local LLM options that can do the same task.
